#-*- coding: utf-8 -*-
typeName = {
        'getDurPrdlstInfoList' : 'DUR품목정보', 
        'getSeobangjeongPartitnAtentInfoList' : '분할주의',
        'getEfcyDplctInfoList' : '효능군중복',
        'getOdsnAtentInfoList' : '노인주의',
        'getMdctnPdAtentInfoList' : '투여기간주의',
        'getCpctyAtentInfoList' : '용량주의',
        'getPwnmTabooInfoList' : '임부금기',
        'getSpcifyAgrdeTabooInfoList' : '특정연령대금기',
        'getUsjntTabooInfoList' : '병용금기'}
typeList = {
        'getDurPrdlstInfoList' : {
            'ITEM_SEQ': '품목기준코드', 
            'ITEM_NAME': '품목명',
            'ENTP_NAME': '업체명',
            'ITEM_PERMIT_DATE': '허가일자',
            'ETC_OTC_CODE': '전문일반',
            'CLASS_NO': '분류',
            'CHART': '성상',
            'BAR_CODE': '표준코드',
            'MATERIAL_NAME': '원료성분',
            'EE_DOC_ID': '제조방법',
            'UD_DOC_ID': '용법용량',
            'NB_DOC_ID': '주의사항',
            'INSERT_FILE': '첨부문서', 
            'STORAGE_METHOD': '저장방법', 
            'VALID_TERM': '유효기간', 
            'REEXAM_TARGET': '재심사대상', 
            'REEXAM_DATE': '재심사기간', 
            'PACK_UNIT': '포장단위', 
            'EDI_CODE': '보험코드', 
            'CANCEL_DATE': '취소일자', 
            'CANCEL_NAME': '상태', 
            'CHANGE_DATE': '변경일자'},
        'getSeobangjeongPartitnAtentInfoList' : {
            'ITEM_SEQ': '품목기준코드',
            'ITEM_NAME': '품목명',
            'ITEM_PERMIT_DATE': '품목허가일자',
            'FORM_CODE_NAME': '제형코드이름',
            'ENTP_NAME': '업체명', 
            'CHART': '성상', 
            'CLASS_CODE': '약효분류코드', 
            'CLASS_NAME': '약효분류', 
            'ETC_OTC_NAME': '전문/일반', 
            'MIX': '단일/복합', 
            'MAIN_INGR': '주성분', 
            'PROHBT_CONTENT': '금기내용', 
            'REMARK': '비고', 
            'CHANGE_DATE': '변경일자'},
        'getEfcyDplctInfoList' : {
            'DUR_SEQ': 'DUR일련번호',
            'EFFECT_NAME': '효능',
            'INGR_CODE': 'DUR성분코드',
            'INGR_NAME': '성분명',
            'INGR_ENG_NAME': 'DUR성분(영문)',
            'FORM_CODE_NAME': '제형구분',
            'MIX': '단일/복합',
            'MIX_INGR': '복합제',
            'ITEM_SEQ': '품목기준코드',
            'ITEM_NAME': '품목명',
            'ITEM_PERMIT_DATE': '품목허가일자',
            'CHART': '성상',
            'ENTP_NAME': '업체명',
            'FORM_CODE': '제형구분코드',
            'FORM_NAME': '제형',
            'ETC_OTC_CODE': '전문일반 구분코드',
            'ETC_OTC_NAME': '전문/일반',
            'CLASS_CODE': '약효분류코드',
            'CLASS_NAME': '약효분류',
            'MAIN_INGR': '주성분',
            'NOTIFICATION_DATE': '고시일자',
            'PROHBT_CONTENT': '금기내용',
            'REMARK': '비고',
            'INGR_ENG_NAME_FULL': 'DUR성분상세명',
            'CHANGE_DATE': '변경일자'},
        'getOdsnAtentInfoList' : {
            'MIX_TYPE': '단일/복합구분',
            'INGR_CODE': 'DUR성분코드',
            'INGR_ENG_NAME': 'DUR성분(영문)',
            'INGR_NAME': 'DUR성분(한글',
            'MIX_INGR': '복합제',
            'FORM_NAME': '형태',
            'ITEM_SEQ': '품목기준코드',
            'ITEM_NAME': '품목명',
            'ITEM_PERMIT_DATE': '품목허가일자',
            'ENTP_NAME': '업체명',
            'CHART': '성상',
            'CLASS_CODE': '약효분류코드',
            'CLASS_NAME': '약효분류',
            'ETC_OTC_NAME': '전문/일반',
            'MAIN_INGR': '주성분',
            'NOTIFICATION_DATE': '고시일자',
            'PROHBT_CONTENT': '금기내용',
            'REMARK': '비고',
            'INGR_ENG_NAME_FULL': 'DUR성분상세명',
            'CHANGE_DATE': '변경일자'},
        'getMdctnPdAtentInfoList' : {
            'MIX_TYPE': '단일/복합구분',
            'INGR_CODE': 'DUR성분코드',
            'INGR_ENG_NAME': 'DUR성분(영문)',
            'INGR_NAME': 'DUR성분(한글)',
            'MIX_INGR': '복합제',
            'FORM_NAME': '형태',
            'ITEM_SEQ': '품목기준코드',
            'ITEM_NAME': '품목명',
            'ITEM_PERMIT_DATE': '품목허가일자',
            'ENTP_NAME': '업체명',
            'CHART': '성상',
            'CLASS_CODE': '약효분류코드',
            'CLASS_NAME': '약효분류',
            'ETC_OTC_NAME': '전문/일반',
            'MAIN_INGR': '주성분',
            'NOTIFICATION_DATE': '고시일자',
            'PROHBT_CONTENT': '금기내용',
            'REMARK': '비고',
            'INGR_ENG_NAME_FULL': 'DUR성분상세명',
            'CHANGE_DATE': '변경일자'},
        'getCpctyAtentInfoList' : {
            'MIX_TYPE': '단일/복합구분',
            'INGR_CODE': 'DUR성분코드',
            'INGR_ENG_NAME': 'DUR성분(영문)',
            'INGR_NAME': 'DUR성분(한글)',
            'MIX_INGR': '복합제',
            'FORM_NAME': '형태',
            'ITEM_SEQ': '품목기준코드',
            'ITEM_NAME': '품목명',
            'ITEM_PERMIT_DATE': '품목허가일자',
            'ENTP_NAME': '업체명',
            'CHART': '성상',
            'CLASS_CODE': '약효분류코드',
            'CLASS_NAME': '약효분류',
            'ETC_OTC_NAME': '전문/일반',
            'MAIN_INGR': '주성분',
            'NOTIFICATION_DATE': '고시일자',
            'PROHBT_CONTENT': '금기내용',
            'REMARK': '비고',
            'INGR_ENG_NAME_FULL': 'DUR성분상세명',
            'CHANGE_DATE': '변경일자'},
        'getPwnmTabooInfoList' : {
            'MIX_TYPE': '단일/복합구분',
            'INGR_CODE': 'DUR성분코드',
            'INGR_ENG_NAME': 'DUR성분(영문)',
            'INGR_NAME': 'DUR성분(한글)',
            'MIX_INGR': '복합제',
            'FORM_NAME': '형태',
            'ITEM_SEQ': '품목기준코드',
            'ITEM_NAME': '품목명',
            'ITEM_PERMIT_DATE': '품목허가일자',
            'ENTP_NAME': '업체명',
            'CHART': '성상',
            'CLASS_CODE': '약효분류코드',
            'CLASS_NAME': '약효분류',
            'ETC_OTC_NAME': '전문/일반',
            'MAIN_INGR': '주성분',
            'NOTIFICATION_DATE': '고시일자',
            'PROHBT_CONTENT': '금기내용',
            'REMARK': '비고',
            'INGR_ENG_NAME_FULL': 'DUR성분상세명',
            'CHANGE_DATE': '변경일자'},
        'getSpcifyAgrdeTabooInfoList' : {
            'MIX_TYPE': '단일/복합구분',
            'INGR_CODE': 'DUR성분코드',
            'INGR_ENG_NAME': 'DUR성분(영문)',
            'INGR_NAME': 'DUR성분(한글)',
            'MIX_INGR': '복합제',
            'FORM_NAME': '형태',
            'ITEM_SEQ': '품목기준코드',
            'ITEM_NAME': '품목명',
            'ITEM_PERMIT_DATE': '품목허가일자',
            'ENTP_NAME': '업체명',
            'CHART': '성상',
            'CLASS_CODE': '약효분류코드',
            'CLASS_NAME': '약효분류',
            'ETC_OTC_NAME': '전문/일반',
            'MAIN_INGR': '주성분',
            'NOTIFICATION_DATE': '고시일자',
            'PROHBT_CONTENT': '금기내용',
            'REMARK': '비고',
            'INGR_ENG_NAME_FULL': 'DUR성분상세명',
            'CHANGE_DATE': '변경일자'},
        'getUsjntTabooInfoList' : {
            'DUR_SEQ': 'DUR일련번호',
            'TYPE_CODE': 'DUR유형코드',
            'MIX': '단일/복합',
            'INGR_CODE': 'DUR성분코드',
            'INGR_KOR_NAME': 'DUR성분',
            'INGR_ENG_NAME': 'DUR성분(영문)',
            'MIX_INGR': '복합제',
            'ITEM_SEQ': '품목기준코드',
            'ITEM_NAME': '품목명',
            'ENTP_NAME': '업체명',
            'CHART': '성상',
            'FORM_CODE': '제형구분코드',
            'ETC_OTC_CODE': '전문일반 구분코드',
            'CLASS_CODE': '약효분류코드',
            'FORM_NAME': '제형',
            'ETC_OTC_NAME': '전문/일반',
            'CLASS_NAME': '약효분류',
            'MAIN_INGR': '주성분',
            'MIXTURE_DUR_SEQ': '병용금기DUR번호',
            'MIXTURE_MIX': '병용금기복합제',
            'MIXTURE_INGR_CODE': '병용금기DUR성분코드',
            'MIXTURE_INGR_KOR_NAME': '병용금기DUR성분',
            'MIXTURE_INGR_ENG_NAME': '병용금기DUR성분(영문)',
            'MIXTURE_ITEM_SEQ': '병용금기품목기준코드',
            'MIXTURE_ITEM_NAME': '병용금기품목명',
            'MIXTURE_ENTP_NAME': '병용금기업체명',
            'MIXTURE_FORM_CODE': '병용금기제형구분코드',
            'MIXTURE_ETC_OTC_CODE': '병용금기전문일반구분코드',
            'MIXTURE_CLASS_CODE': '병용금기약효분류코드',
            'MIXTURE_FORM_NAME': '병용금기제형',
            'MIXTURE_ETC_OTC_NAME': '병용금기전문/일반',
            'MIXTURE_CLASS_NAME': '병용금기약효분류',
            'MIXTURE_MAIN_INGR': '병용금기주성분',
            'NOTIFICATION_DATE': '고시일자',
            'PROHBT_CONTENT': '금기내용',
            'REMARK': '비고',
            'ITEM_PERMIT_DATE': '품목허가일자',
            'MIXTURE_ITEM_PERMIT_DATE': '병용금기품목허가일자',
            'MIXTURE_CHART': '병용금기성상',
            'CHANGE_DATE': '변경일자',
            'MIXTURE_CHANGE_DATE': '병용변경일자'}
        
        }
